### ISSUE TITLE
Error when enabling OIDC authentication

### ISSUE THREAD

**Issue by johnnychoque** [ging/fiware-idm#258]
Enabling the "Open ID Connect Authentication" checkbox during the creation of the application generates the following error:

`Error: ENOENT: no such file or directory, mkdir './certs/applications'.
    at Object.mkdirSync (fs.js:1013:3)
    at generate_app_certificates (/home/administrator/fiware-idm/controllers/web/applications.js:916:8)`

The error is resolved by manually creating the './certs/applications' directory. I think the best option is to add code in controllers/web/applications.js:916:8 to create that directory using fs.mkdir before using fs.mkdirSync.

**Comment by nikosft** [comment]
Related to that: Why a certificate is generated per application?
