### ISSUE TITLE
docker image 8.3.2 openssl not found

### ISSUE THREAD

**Issue by nikosft** [ging/fiware-idm#314]
In this image version many operation fail because `openssl is not found` I executed bash the fiware-keyrock container and I manually installed openssl. Then the issue was resolved.

**Comment by nikosft** [comment]
Openssl was installed using the following commands. From the host

```
docker exec -it fiware-keyrock bash
```

Then
```
apt-get update
apt-get install openssl
```

**Comment by bramk** [comment]
Thanks @nikosft! Just wish I had found your issue earlier. 

Image 8.3.3. still affected
```
GET /health 200 5.500 ms - 13747
POST /idm/applications - - ms - -
2023-06-01T12:30:18.627Z idm:web-session_controller --> login_required
2023-06-01T12:30:18.627Z idm:web-session_controller --> password_check_date
2023-06-01T12:30:18.627Z idm:web-application_controller --> create
2023-06-01T12:30:18.628Z idm:web-application_controller --> generate_app_certificates
2023-06-01T12:30:18.644Z idm:web-application_controller Error:  Error: Command failed: openssl genrsa -out certs/applications/5936f76d-a9ac-4549-8399-c094b94d094a-oidc-key.pem 2048 && openssl req -new -sha256 -key certs/applications/5936f76d-a9ac-4549-8399-c094b94d094a-oidc-key.pem -out certs/applications/5936f76d-a9ac-4549-8399-c094b94d094a-oidc-csr.pem -subj "/C=IK/ST=World/L=World/O=qqq/OU=qqq/CN=https" && openssl x509 -days 365 -req -in certs/applications/5936f76d-a9ac-4549-8399-c094b94d094a-oidc-csr.pem -signkey certs/applications/5936f76d-a9ac-4549-8399-c094b94d094a-oidc-key.pem -out certs/applications/5936f76d-a9ac-4549-8399-c094b94d094a-oidc-cert.pem
/bin/sh: 1: openssl: not found

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Socket.<anonymous> (internal/child_process.js:446:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'openssl genrsa -out certs/applications/5936f76d-a9ac-4549-8399-c094b94d094a-oidc-key.pem 2048 && openssl req -new -sha256 -key certs/applications/5936f76d-a9ac-4549-8399-c094b94d094a-oidc-key.pem -out certs/applications/5936f76d-a9ac-4549-8399-c094b94d094a-oidc-csr.pem -subj "/C=IK/ST=World/L=World/O=qqq/OU=qqq/CN=https" && openssl x509 -days 365 -req -in certs/applications/5936f76d-a9ac-4549-8399-c094b94d094a-oidc-csr.pem -signkey certs/applications/5936f76d-a9ac-4549-8399-c094b94d094a-oidc-key.pem -out certs/applications/5936f76d-a9ac-4549-8399-c094b94d094a-oidc-cert.pem'
}
(node:19) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /opt/fiware-idm/controllers/web/applications.js:483:26
```
