### ISSUE TITLE
cannot start the  fiware-idm

### ISSUE THREAD

**Issue by raiuli** [ging/fiware-idm#5]
npm start

> idm@0.0.0 start /home/raiuli/fiware-idm
> node ./bin/www

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
/home/raiuli/fiware-idm/node_modules/nodemailer/lib/mailer/index.js:31
            compile: [(...args) => this._convertDataImages(...args)],
                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/raiuli/fiware-idm/node_modules/nodemailer/lib/nodemailer.js:3:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/raiuli/fiware-idm/lib/mailer.js:1:80)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/raiuli/fiware-idm/lib/email.js:1:76)

npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! idm@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the idm@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the idm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs idm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls idm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/raiuli/fiware-idm/npm-debug.log

**Comment by TheNextLVL** [comment]
See the docker-entrypoint.sh, first you need import the DB
```
npm run create_db
npm run migrate_db
npm run seed_db

sudo npm start
```

**Comment by raiuli** [comment]
the error solved after upgrading the npm and node to following version 
node v8.11.1
npm -v5.6.0

i am using ubuntu 16.04LTS
