### ISSUE TITLE
Invalid scope: Requested scope is invalid

### ISSUE THREAD

**Issue by ibstelix** [ging/fiware-idm#66]
Hello dear support,
please help 2 weeks i am  struggling to get work Biz Ecosystem with my local fiware-idm.
It's working perfectly with the online lab but with my local fiware-idm it's trowing:

>  invalid_scope: Invalid scope: Requested scope is invalid
    at new InvalidScopeError (/opt/fiware-idm/node_modules/oauth2-server/lib/errors/invalid-scope-error.js:25:14)
    at /opt/fiware-idm/node_modules/oauth2-server/lib/grant-types/abstract-grant-type.js:117:17
    at tryCatcher (/opt/fiware-idm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/fiware-idm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/fiware-idm/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/opt/fiware-idm/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/opt/fiware-idm/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/opt/fiware-idm/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/fiware-idm/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
  statusCode: 400,
  status: 400,
  code: 400,
  message: 'Invalid scope: Requested scope is invalid',
  name: 'invalid_scope'

**Comment by ibstelix** [comment]
It worked when i sent "permanent" as scope

**Comment by johnnychoque** [comment]
Hi @ibstelix,
I get the same error with Biz Ecosystem. I understand that you have set the token type to permanent. I tried your suggestion but it did not work in my case.
what version of Fiware-IDM do you use?
I have tried it on versions 7.9.2 and 8.1.0 and both get the same error.
