### ISSUE TITLE
Please update the docker-compose to use the last version with regex

### ISSUE THREAD

**Issue by tmontanaro** [ging/fiware-idm#98]
Could you please update the docker-compose to use the last version of the IdM?

I tried to use the last IdM version within a docker container (by setting v. 7.7.0 in the docker-compose defined in your repository) but I get the following error (shown in the log) when I try to use the GUI to insert a new application:
```

Executing (default): INSERT INTO `oauth_client` (`id`,`name`,`description`,`url`,`redirect_uri`,`redirect_sign_out_uri`,`secret`,`image`,`grant_type`,`response_type`) VALUES ('3bcb93ba-9221-4066-a6c9-a93142ba0ea7','App Prova','App Prova','http://192.168.1.146','http://192.168.1.178','','7008e221-bfe5-4b0d-8f55-8d56f263917c','default','authorization_code,implicit,password,client_credentials,refresh_token','code,token');
Executing (default): INSERT INTO `role_assignment` (`id`,`role_id`,`user_id`,`oauth_client_id`) VALUES (DEFAULT,'provider','ad374a02-8df5-4c54-a4be-fc242fc45b6f','3bcb93ba-9221-4066-a6c9-a93142ba0ea7');
Mon, 20 May 2019 17:21:19 GMT idm:web-application_controller Error:  { SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`idm`.`role_assignment`, CONSTRAINT `role_assignment_ibfk_4` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE)
    at Query.formatError (/opt/fiware-idm/node_modules/sequelize/lib/dialects/mysql/query.js:236:16)
    at Query.handler [as onResult] (/opt/fiware-idm/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/opt/fiware-idm/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:455:32)
    at PacketParser.onPacket (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:73:18)
    at PacketParser.executeStart (/opt/fiware-idm/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:80:31)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
  name: 'SequelizeForeignKeyConstraintError',
  parent: 
   { Error: Cannot add or update a child row: a foreign key constraint fails (`idm`.`role_assignment`, CONSTRAINT `role_assignment_ibfk_4` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE)
    at Packet.asError (/opt/fiware-idm/node_modules/mysql2/lib/packets/packet.js:684:17)
    at Query.execute (/opt/fiware-idm/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:455:32)
    at PacketParser.onPacket (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:73:18)
    at PacketParser.executeStart (/opt/fiware-idm/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:80:31)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
     code: 'ER_NO_REFERENCED_ROW_2',
     errno: 1452,
     sqlState: '23000',
     sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`idm`.`role_assignment`, CONSTRAINT `role_assignment_ibfk_4` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE)',
     sql: 'INSERT INTO `role_assignment` (`id`,`role_id`,`user_id`,`oauth_client_id`) VALUES (DEFAULT,\'provider\',\'ad374a02-8df5-4c54-a4be-fc242fc45b6f\',\'3bcb93ba-9221-4066-a6c9-a93142ba0ea7\');' },
(node:312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Maybe it is only a problem related to the creation of the database!

**Comment by apozohue10** [comment]
Hi, sorry for the delay! The version of IdM has been updated to 7.7.0!
